### ISSUE TITLE
switch off Archivematica Staging outside office hours, like prod

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/editorial-photography-ingest#28]
The Archivematica production instance shuts down overnight.  This saves money and gives it a chance to have a little rest and refresh itself.

There is no such respite available for the staging instance.  When I first tried running one of these transfers into staging, it didn't work because the application was all tuckered out from staying awake permanently for several months.

This should be switched off with at least the same schedule as production. Given how little it is used, it should probably be switched off until we explicitly want it.

**Comment by agnesgaroux** [comment]
This https://github.com/wellcomecollection/archivematica-infrastructure/pull/151 aligns the staging scale up/down with the production situation
Looking at maybe reducing costs further by only starting the staging stuff when actively needed
